# Blintz base: the square joining the four edge midpoints.
# Generated by apps/web/scripts/seeds/geometry.ts (blintzBase).

1 0 0 1 0
1 1 0 1 1
1 1 1 0 1
1 0 1 0 0
3 0.5 0 1 0.5
3 1 0.5 0.5 1
3 0.5 1 0 0.5
3 0 0.5 0.5 0
