# Kite base: a diagonal plus two 22.5 degree creases from one corner.
# Generated by apps/web/scripts/seeds/geometry.ts (kiteBase).

1 0 0 1 0
1 1 0 1 1
1 1 1 0 1
1 0 1 0 0
3 0 0 1 1
2 0 0 1 0.414213562
2 0 0 0.414213562 1
