# Waterbomb base, the eight-crease pattern as normally drawn.
# Generated by apps/web/scripts/seeds/geometry.ts (waterbombBase).

1 0 0 1 0
1 1 0 1 1
1 1 1 0 1
1 0 1 0 0
3 0 0 1 1
3 1 0 0 1
2 0.5 0 0.5 1
2 0 0.5 1 0.5
