import Link from "next/link";
import type { PatternSummary } from "@/lib/patterns";

export function PatternCard({ pattern }: { readonly pattern: PatternSummary }) {
  return (
    <Link
      href={`/p/${pattern.id}`}
      className="group block overflow-hidden rounded-lg border transition hover:shadow-md"
      style={{ borderColor: "var(--border)", background: "var(--surface-raised)" }}
    >
      <div className="aspect-square w-full p-3">
        {/* eslint-disable-next-line @next/next/no-img-element -- the thumbnail is SVG generated by our own renderer */}
        <img
          src={`/p/${pattern.id}/thumbnail`}
          alt={`Crease pattern for ${pattern.title}`}
          className="size-full object-contain transition group-hover:scale-[1.02]"
          loading="lazy"
        />
      </div>
      <div className="border-t px-4 py-3" style={{ borderColor: "var(--border)" }}>
        <h3 className="truncate font-medium">{pattern.title}</h3>
        <p className="truncate text-sm" style={{ color: "var(--text-muted)" }}>
          {pattern.designer}
        </p>
        <p className="mt-1 text-xs tabular-nums" style={{ color: "var(--text-muted)" }}>
          {pattern.edgeCount} creases · {pattern.mountainCount}M / {pattern.valleyCount}V
          {pattern.flatFoldable ? " · flat-foldable" : ""}
        </p>
      </div>
    </Link>
  );
}
