import {
  accordion,
  birdBase,
  blintzBase,
  gridPleat,
  kiteBase,
  miuraOri,
  toCpText,
  waterbombBase,
  type CpLine,
} from "./geometry";

/**
 * The seeded pattern library (DESIGN.md §10 Phase 1, "seed ~100
 * public-domain/CC patterns by hand").
 *
 * Everything here is either a traditional origami base or a published
 * mathematical/engineering pattern: geometry that is genuinely public, not
 * anyone's competition model. Growing this to ~100 means the designer outreach
 * §11 Q1 describes, not more code: we are not going to invent crease patterns
 * and attribute them to people.
 *
 * `flatFoldable` is the expected verdict from `@kamibase/core`'s Maekawa and
 * Kawasaki checks. The seed script asserts it, so a generator that quietly
 * stops producing a foldable pattern fails the build instead of shipping.
 */
export interface Seed {
  readonly id: string;
  readonly title: string;
  readonly designer: string;
  readonly description: string;
  readonly lines: readonly CpLine[];
  readonly header: string;
  /** Expected result of the local flat-foldability checks. */
  readonly flatFoldable: boolean;
  readonly paper: {
    readonly shape: "square";
    readonly gridSystem?: "none" | "square" | "box-pleat" | "22.5" | "hex" | "arbitrary";
    readonly gridDivisions?: number;
    readonly recommendedSizeMm?: number;
    readonly recommendedPaper?: string;
  };
  readonly difficulty?: { readonly rating: number; readonly estimatedMinutes?: number };
  readonly taxonomy: {
    readonly subject?: readonly string[];
    readonly techniques?: readonly string[];
    readonly tags?: readonly string[];
  };
  readonly license: {
    readonly spdx: string;
    readonly foldingAllowed: "personal" | "commercial" | "any";
    readonly redistribution: "none" | "with-attribution" | "any";
  };
  readonly sourceUrl?: string;
  readonly collapseNotes?: string;
}

const PUBLIC_DOMAIN = {
  spdx: "CC0-1.0",
  foldingAllowed: "any",
  redistribution: "any",
} as const;

function miuraSeed(columns: number, bands: number, rating: number): Seed {
  return {
    id: `miura-ori-${columns}x${bands}`,
    title: `Miura-ori ${columns}×${bands}`,
    designer: "Kōryō Miura",
    description:
      `A ${columns}×${bands} Miura fold, the rigid-foldable parallelogram ` +
      "tessellation used for deployable solar arrays and folding maps. Every " +
      "interior vertex carries three creases of one kind and one of the other.",
    lines: miuraOri(columns, bands),
    header:
      `Miura-ori, ${columns} columns x ${bands} bands, on the unit square.\n` +
      "Generated by apps/web/scripts/seeds/geometry.ts (miuraOri).",
    flatFoldable: true,
    paper: {
      shape: "square",
      gridSystem: "arbitrary",
      recommendedSizeMm: 210,
      recommendedPaper: "Kraft or elephant hide, 80–110gsm",
    },
    difficulty: { rating, estimatedMinutes: 15 * bands },
    taxonomy: {
      subject: ["tessellation"],
      techniques: ["pleating", "rigid-foldable"],
      tags: ["miura", "deployable", "tessellation"],
    },
    license: PUBLIC_DOMAIN,
    sourceUrl: "https://en.wikipedia.org/wiki/Miura_fold",
    collapseNotes:
      "Pre-crease every zigzag line first, then collapse column by column. " +
      "The vertical creases change direction at each zigzag, which is what " +
      "makes the fold rigid.",
  };
}

function accordionSeed(folds: number): Seed {
  return {
    id: `accordion-${folds}`,
    title: `Accordion pleat, ${folds} creases`,
    designer: "Traditional",
    description:
      `${folds} parallel creases alternating mountain and valley. The simplest ` +
      "pleat there is, and a good print-to-scale test for a new paper.",
    lines: accordion(folds),
    header:
      `Accordion pleat of ${folds} creases across the unit square.\n` +
      "Generated by apps/web/scripts/seeds/geometry.ts (accordion).",
    flatFoldable: true,
    paper: { shape: "square", gridSystem: "square", gridDivisions: folds + 1 },
    difficulty: { rating: 1, estimatedMinutes: 5 },
    taxonomy: {
      subject: ["study"],
      techniques: ["pleating"],
      tags: ["pleat", "beginner"],
    },
    license: PUBLIC_DOMAIN,
  };
}

export const SEEDS: readonly Seed[] = [
  {
    id: "bird-base",
    title: "Bird base",
    designer: "Traditional",
    description:
      "The base the traditional crane is folded from: two diagonals, two book " +
      "folds and eight petal-fold creases at 22.5°. Fold this and you are four " +
      "steps from a crane.",
    lines: birdBase(),
    header:
      "Bird base (traditional crane base) on the unit square.\n" +
      "Generated by apps/web/scripts/seeds/geometry.ts (birdBase).",
    flatFoldable: true,
    paper: {
      shape: "square",
      gridSystem: "22.5",
      recommendedSizeMm: 150,
      recommendedPaper: "Kami, 60gsm",
    },
    difficulty: { rating: 2, estimatedMinutes: 10 },
    taxonomy: {
      subject: ["base", "bird"],
      techniques: ["petal-fold", "preliminary-base"],
      tags: ["crane", "traditional", "base"],
    },
    license: PUBLIC_DOMAIN,
    collapseNotes:
      "Collapse to the preliminary base first, then petal-fold front and back.",
  },
  {
    id: "waterbomb-base",
    title: "Waterbomb base",
    designer: "Traditional",
    description:
      "Both diagonals and both book folds, drawn the way every book draws them. " +
      "Structurally clean, but the centre carries four mountains and four " +
      "valleys, which Maekawa's theorem says cannot fold flat as drawn.",
    lines: waterbombBase(),
    header:
      "Waterbomb base, the eight-crease pattern as normally drawn.\n" +
      "Generated by apps/web/scripts/seeds/geometry.ts (waterbombBase).",
    flatFoldable: false,
    paper: { shape: "square", gridSystem: "22.5", recommendedSizeMm: 150 },
    difficulty: { rating: 1, estimatedMinutes: 5 },
    taxonomy: {
      subject: ["base"],
      techniques: ["collapse"],
      tags: ["waterbomb", "traditional", "base"],
    },
    license: PUBLIC_DOMAIN,
  },
  {
    id: "blintz-base",
    title: "Blintz base",
    designer: "Traditional",
    description:
      "All four corners folded to the centre. Every crease ends on the paper " +
      "edge, so there is not a single interior vertex to check.",
    lines: blintzBase(),
    header:
      "Blintz base: the square joining the four edge midpoints.\n" +
      "Generated by apps/web/scripts/seeds/geometry.ts (blintzBase).",
    flatFoldable: true,
    paper: { shape: "square", gridSystem: "22.5", recommendedSizeMm: 150 },
    difficulty: { rating: 1, estimatedMinutes: 3 },
    taxonomy: {
      subject: ["base"],
      techniques: ["blintz"],
      tags: ["blintz", "traditional", "base", "beginner"],
    },
    license: PUBLIC_DOMAIN,
  },
  {
    id: "kite-base",
    title: "Kite base",
    designer: "Traditional",
    description:
      "One diagonal with the two adjacent edges folded in to meet it. The " +
      "starting point for a startling number of traditional models.",
    lines: kiteBase(),
    header:
      "Kite base: a diagonal plus two 22.5 degree creases from one corner.\n" +
      "Generated by apps/web/scripts/seeds/geometry.ts (kiteBase).",
    flatFoldable: true,
    paper: { shape: "square", gridSystem: "22.5", recommendedSizeMm: 150 },
    difficulty: { rating: 1, estimatedMinutes: 3 },
    taxonomy: {
      subject: ["base"],
      techniques: ["kite"],
      tags: ["kite", "traditional", "base", "beginner"],
    },
    license: PUBLIC_DOMAIN,
  },
  miuraSeed(4, 3, 2),
  miuraSeed(6, 4, 3),
  miuraSeed(8, 6, 4),
  miuraSeed(12, 8, 5),
  miuraSeed(16, 12, 6),
  accordionSeed(8),
  accordionSeed(16),
  accordionSeed(32),
  {
    id: "reference-grid-8",
    title: "8×8 reference grid",
    designer: "Traditional",
    description:
      "A square grid of pre-creases, the scaffolding box-pleated designs are " +
      "built on. It is a reference grid, not a model: crossing pleats put four " +
      "creases of two kinds at every intersection, so it does not fold flat and " +
      "is not meant to.",
    lines: gridPleat(8),
    header:
      "8x8 square reference grid on the unit square.\n" +
      "Generated by apps/web/scripts/seeds/geometry.ts (gridPleat).",
    flatFoldable: false,
    paper: {
      shape: "square",
      gridSystem: "square",
      gridDivisions: 8,
      recommendedSizeMm: 250,
    },
    difficulty: { rating: 2, estimatedMinutes: 20 },
    taxonomy: {
      subject: ["study"],
      techniques: ["box-pleating", "pleating"],
      tags: ["grid", "precrease", "box-pleat"],
    },
    license: PUBLIC_DOMAIN,
  },
];

export function seedCpText(seed: Seed): string {
  return toCpText(seed.lines, seed.header);
}
